### PR TITLE
[skip-ci] Include data folder

### PR DESCRIPTION
**Pull request by dcherian**

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@dcherian Will you be yanking v0.7.8?

**Comment by dcherian** [comment]
Just did. thanks!

**Comment by dcherian** [comment]
@Zeitsperre can you try out the wheel built on this branch please? It looks OK to me...

**Comment by Zeitsperre** [comment]
@decherian sure thing! Give me 15 mins

**Pull request merged**
