### PR TITLE
custom unit formatter

### PR DESCRIPTION
**Pull request by keewis**
The combination of `pint`'s new-ish custom formatter feature and `xclim`'s unit formatting function (see Ouranosinc/xclim#780). Only the short formatter for now because `pint` does not pass the unit modifier to the formatter (i.e. to support both short and long version, we need a change to `pint` first).

- [x] Tests added
- [x] fully documented
- [x] changelog updated
- [x] licensing: how do you want to handle this? At the moment there's a module docstring declaring everything in the module to be vendored from `metpy`, but that's not true anymore.

cc @aulemahal

### CODE REVIEW

**Comment by aulemahal** [comment]
Nice! If your last point was about "sublicensing" xclim, I don't think it's really needed. I mean, as a core dev of xclim, I am totally ok with cf-xarray simply copying the code. To be certain we can ask @huard, who I think wrote this function (`pint2cfunits`).

**Comment by keewis** [comment]
that was directed at @dcherian: I only have experience with vendoring code (which is including the code *without* asking for permission) so I wasn't sure what to do in this case.

A simple comment stating that "this was moved here from xclim", or modifying the notice about `metpy` to not cover everything in the module might probably suffice?

**Comment by dcherian** [comment]
Not sure what the right answer is.

Practically,  I think modifying the notice at the top to specifically mention this function should be OK? We can also add a. comment above this function to make it extra clear.

It does seem like we need to include the text of the BSD-3-clause license somewhere

**Comment by keewis** [comment]
not sure if that's the best way, but I think if the `xclim` developers (in this case @huard?) tell us it's fine without that we would be relicensing it to `cf-xarray`'s license?

**Comment by dcherian** [comment]
xclim and cf_xarray are both apache-2 and apache-2 allows redistributing as long. as the new. license is compatible with apache-2

The super safe thing would be to create a new  `formatting.py` and  import it here.

**Comment by keewis** [comment]
> The super safe thing would be to create a new `formatting.py` and import it here.

or we reorganize the current one to not have the notice at the top, but divide it into sections containing code from the same source. For now, this is easy: there's no dependency between the unit parsing and the unit formatting code.

**Comment by dcherian** [comment]
OK sounds good to me.

**Comment by keewis** [comment]
not sure what the issue with RTD is, but in any case this should be ready for another round of reviews.

**Comment by dcherian** [comment]
LGTM.

Is pint likely to support passing modifiers soon?  Should we instead register `cfshort` and `cflong`?

**Comment by keewis** [comment]
that depends on whether or not I can send in a PR... I think that should not be too much effort, but I won't really know until I work on it

**Comment by dcherian** [comment]
Thanks @keewis. This is a great contribution

**Comment by huard** [comment]
For the record, I'm happy to see this go into xarray.

**Pull request merged**
