### PR TITLE
Allow any cell measure

### PR DESCRIPTION
**Pull request by malmans2**
See https://github.com/xarray-contrib/cf-xarray/issues/99#issuecomment-727984869

### CODE REVIEW

**Comment by malmans2** [comment]
Not sure what's up with the pre-commit action. It's running fine on my machine.

**Review by malmans2 — COMMENTED** [review]
@dcherian I've commented out this check so `get_associated_variable_names` can use `_get_measure`. In the `_get_measure`  docstring there are two arguments that I don't think are actually used: `error` and `default`. Do you want to implement those and use `error=False` in  `get_associated_variable_names` , or we can just get rid of the `valid_keys` check?

**Comment by malmans2** [comment]
Here is the part I've commented out:
https://github.com/xarray-contrib/cf-xarray/blob/86f3e511fbef9c70158afc767886f52ee5113d2d/cf_xarray/accessor.py#L339-L370

**Comment by malmans2** [comment]
Actually, I realized I don't have to use `_get_measure` in `get_associated_variable_names`.
Sorry, this was a bit messy, but I think it's good to go now.

**Comment by dcherian** [comment]
Thanks @malmans2 . I think we could allow indexing `.cf.cell_measures` by any arbitrary cell measure name, not just area, volume. WDYT? 

We could also show these extra measures in `.cf.describe()`

**Comment by dcherian** [comment]
Actually this will take some effort. This LGTM for now.

**Pull request merged**
