### PR TITLE
Don't look for `T` in sgrid axes

### PR DESCRIPTION
**Pull request by kthyng**
cf-xarray is not finding T as a time axis due to a KeyError. This first checks to see if the key is in sgrid_axes before using that.

Closes https://github.com/xarray-contrib/cf-xarray/issues/434

### CODE REVIEW

**Comment by kthyng** [comment]
@dcherian the errors don't look related as far as I can tell.

**Comment by kthyng** [comment]
I'm not sure how other people are using `cf-xarray` currently because this is a total blocker for me!

**Comment by dcherian** [comment]
This looks right, can you add a test.

Presumably you have an sgrid dataset with the `grid_topology` variable, Anyone without it is unaffected

**Comment by kthyng** [comment]
Ok in modifying a test to check for this I was forced to look into `parse_axes` some – I'm not familiar with the grid topology stuff at all. But it looks like X, Y, and Z are the only options anyway for key so I put them directly into `_get_axis_coord`.

Does that work?

**Comment by dcherian** [comment]
Yes I think that's right.

**Pull request merged**
